on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: aliyunoss
    steps:
      - uses: actions/checkout@v3
      - name: upload to aliyun oss
        # You may pin to the exact commit or the version.
        # uses: JayMeDotDot/aliyun-OSS-deployer@49aac05eb7d0fa0c384ac6d140633e274a5b2c80
        uses: fangbinwei/aliyun-oss-website-action@v1
        with:
          # 通过阿里云控制台创建的AccessKey ID
          accessKeyId: ${{ secrets.ACCESS_KEY_ID }}
          # 通过阿里云控制台创建的AccessKey Secret
          accessKeySecret: ${{ secrets.ACCESS_KEY_SECRET }}
          # 通过控制台或PutBucket创建的Bucket
          bucket: ${{ secrets.BUCKET }} # optional
          # OSS访问域名
          endpoint: ${{ secrets.ENDPOINT }}
          folder: src
